GET  http://localhost:8080/users HTTP/1.1
content-type: application/json

###

GET  http://localhost:8080/users/1 HTTP/1.1
content-type: application/json

# 200 (OK)
# 404 (Not Found)

###

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{"name":"some name","age":24,"friends":[]}

###

PATCH http://localhost:8080/users/1001 HTTP/1.1
content-type: application/json

{"age": 32}

###

DELETE http://localhost:8080/users/1001 HTTP/1.1
content-type: application/json

# 200 (OK)
# 404 (Not Found)

###

PUT  http://localhost:8080/users/1001/friends HTTP/1.1
content-type: application/json

{"id":"1002"}

###

GET  http://localhost:8080/users/1001/friends HTTP/1.1
content-type: application/json

# 200 (OK)
# 404 (Not Found)

###

DELETE http://localhost:8080/users/1001/friends/1002 HTTP/1.1
content-type: application/json

# 200 (OK)
# 404 (Not Found)